#ItemMerge
Amount Color: "&e&l"
ItemName Color: "&e&l"

#Discord Config
Webhook Url: "https://discord.com/api/webhooks/881736314028982292/dx7rKUyrH994PN36oJ7R6Yy-popLUP4qPZyZBInNE6hK4LdFIdTJ5FHgRlCJdhTIAtAK"
Webhook AvatarUrl: "https://play-lh.googleusercontent.com/VSwHQjcAttxsLE47RuS4PqpC4LT7lCoSjE7Hx5AW_yCxtDvcnsHHvm5CTuL5BPN-uRTP"
Webhook Username: "Minecraft Server"